### ISSUE TITLE
Inconsistent level for naics Sectors

### ISSUE THREAD

**Issue by julfersnlt** [LEDApplications/lehd-schema#17]
In `label_industry.csv`, naics Sectors get `ind_level=2`, but most other places, they are `ind_level=S`.

| Where | Sector ind_level |
|-------|------------------|
| label_industry	| 2 |
| label_ind_level	| S |
| agg_level			| S |
| j2j data 			| S |
| qwi data 			| S |

It would be better to use the same value everywhere.

**Comment by julfersnlt** [comment]
This is a breaking change regardless of where we change it, but I suspect it's much less likely to cause problems if we change the `label_industry.csv` than if we change the data.

**Comment by srt1** [comment]
@julfersnlt 

Thank you for noting this (many moons ago). This is a table that is created by the production system, and it was probably an oversight that we neglected to remap the code from 2 to S. We are changing the NAICS codes to 2022 next cycle, so I plan to have this corrected at the same time - so that will be for the data released in R2023Q1. 
Will that cause any issues for the web tools?

**Comment by srt1** [comment]
@heathhayward , @jodyhoonstarr 

Just popping you into the conversation on this one. I have requested Camille to make changes to production code to fix this output csv. Please let me know if there are any issues with fixing this now. Thanks.

**Comment by srt1** [comment]
Work on this is under Redmine ticket 7595

**Comment by julfersnlt** [comment]
Good morning @srt1, I expect some changes will be required but I'll need to take a little time to look at how they [the web tools] use label_industry.csv to say for sure. @heathhayward @jodyhoonstarr I filed [#10606](https://censusnlt.plan.io/issues/10606) and [#10607](https://censusnlt.plan.io/issues/10607) for our tracking.

**Comment by jodyhoonstarr** [comment]
@julfersnlt this should be fixed in the current version 4.10.0 if you wanna consider how it would affect the apps
