### ISSUE TITLE
Add short description to NAICS

### ISSUE THREAD

**Issue by jodyhoonstarr** [LEDApplications/lehd-schema#26]
From a PSEO user who requested some additional info about what the NAICS labels actually mean. 

E.g. from the NAICS Descriptions file for `11- Agriculture, Forestry, Fishing and Hunting`
```text
The Sector as a Whole

The Agriculture, Forestry, Fishing and Hunting sector comprises establishments primarily engaged in 
growing crops, raising animals, harvesting timber, and harvesting fish and other animals from a farm, 
ranch, or their natural habitats.
```

[NAICS files](https://www.census.gov/naics/?48967)

**Comment by srt1** [comment]
Those long descriptions of the industries can be found in the NAICS page that we link to. It's not part of the download I get with the short labels. I don't particularly want to do a lot of work to figure out how to wrangle the long descriptions.

**Comment by srt1** [comment]
Since PSEO is at the NAICS sector only, you might consider providing links to the following pages:

https://www.census.gov/naics/?input=11&year=2022&details=11
https://www.census.gov/naics/?input=21&year=2022&details=21
...
https://www.census.gov/naics/?input=31&year=2022&details=31
...
_etc._

It looks like if you substitute the industry code (first two digits for the concatenated ones) it will go to the right place.

**Comment by jodyhoonstarr** [comment]
That's a good idea. Don't wanna manage any more of this than we have to.

**Comment by srt1** [comment]
Yes, I do not want to suck those long descriptions into the schema. There might be a better way to point directly to the long descriptions (from the PSEO app, I mean, probably not the schema), but I don't think we want to go any farther than the existing Census NAICS site.

**Comment by jodyhoonstarr** [comment]
Schema docs already have a link to the Census NAICS site so this can be a PSEO app thing to think about.
