### ISSUE TITLE
File name csv content misinterpreted as markup

### ISSUE THREAD

**Issue by julfersnlt** [LEDApplications/lehd-schema#33]
Rendering to [`naming_convention.csv`](https://github.com/LEDApplications/lehd-schema/blob/main/src/naming_convention.csv#L3) to html drops some parts of the `qwi_*` raw data file names. It should display as `[type]_[geohi]_[demo]_[fas]_[geocat]_[indcat]_[ownercat]_[sa]`:

![Screenshot 2023-05-10 143523](https://github.com/LEDApplications/lehd-schema/assets/86742602/95403de2-0728-4d8e-b0f8-5b4feef3d23d)

**Comment by jodyhoonstarr** [comment]
I've looked into this one a few times and haven't found a quick fix. The gist seems to be that the special chars can be escaped

1. via [substitutions](https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/)
```adoc
[subs=specialchars]
rendered properly: [type]_[geohi]_[demo]_[fas]_[geocat]_[indcat]_[ownercat]_[sa]
```

2. via [pass](https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/)

I can't find a way to make either of these work nice when we import the table data from a csv into the document via `include::naming_convention.csv[]`.

@srt1 @heathhayward can we kill off the [naming_convention.csv](https://lehd.ces.census.gov/data/schema/latest/naming_convention.csv) file and put the content directly in the docs as a plain table?

**Comment by heathhayward** [comment]
I'm ok with that solution. We should add a period to the end of all of the "Description" rows while we are at this. There's also a space in front of both PSEO row's descriptions that should be removed.

**Comment by srt1** [comment]
Not sure I completely get the issue, but whatever works, I guess. This was presumably originally designed as a csv so that it would be machine-readable, and I presume a table on the page would be harder to access from that perspective, but it's kind of hard to imagine how this table would really be used in an automated way. It is pretty quirky. I can't imagine any users (beyond Lars?) have built systems to read that table and use it to access the data. So I guess do what you need to do.

Thanks,
Stephen
________________________________
